/*
# Seed game catalog for Boutique de Desteur Game

Inserts games across all categories: Naruto, Call of Duty, Injustice, Sport, Action, Survival, Minecraft.
No RPG games included per requirements.
*/

INSERT INTO games (title, category, genre, price, description, image_url, rating, platform, featured, stock) VALUES
  ('Naruto Shippuden: Ultimate Ninja Storm 4', 'naruto', 'Naruto', 15000, 'Combattez avec vos ninjas préférés dans ce jeu de combat basé sur la saga Naruto Shippuden. Graphismes spectaculaires et combats épiques.', 'https://images.pexels.com/photos/37300565/pexels-photo-37300565.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 4.8, 'PS4 / PS5 / Xbox', true, 50),
  ('Naruto to Boruto: Shinobi Striker', 'naruto', 'Naruto', 18000, 'Un jeu multijoueur où vous créez votre propre ninja et affrontez d''autres joueurs en ligne dans des batailles de team.', 'https://images.pexels.com/photos/5971303/pexels-photo-5971303.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 4.3, 'PS4 / PC', false, 35),
  ('Naruto: Ultimate Ninja Storm Trilogy', 'naruto', 'Naruto', 12000, 'Revivez les trois premières aventures de Naruto dans cette compilation de combat à l''animation bluffante.', 'https://images.pexels.com/photos/6778700/pexels-photo-6778700.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 4.5, 'Switch / PS4', false, 40),
  ('Call of Duty: Modern Warfare III', 'call_of_duty', 'Call of Duty', 25000, 'Le retour de l''action militaire la plus intense. Mode campagne, multijoueur et Warzone réunis dans un seul jeu.', 'https://images.pexels.com/photos/18602380/pexels-photo-18602380.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 4.7, 'PS5 / Xbox / PC', true, 60),
  ('Call of Duty: Black Ops Cold War', 'call_of_duty', 'Call of Duty', 20000, 'Plongez dans la Guerre Froide avec des opérations secrètes, un mode zombie et un multijoueur explosif.', 'https://images.pexels.com/photos/29656080/pexels-photo-29656080.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 4.4, 'PS5 / Xbox / PC', false, 45),
  ('Call of Duty: Vanguard', 'call_of_duty', 'Call of Duty', 22000, 'Combattez sur tous les fronts de la Seconde Guerre mondiale avec un casting international de soldats d''élite.', 'https://images.pexels.com/photos/5697210/pexels-photo-5697210.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 4.2, 'PS5 / Xbox / PC', false, 30),
  ('Injustice 2', 'injustice', 'Injustice', 20000, 'Affrontez vos héros et vilains DC préférés dans ce jeu de combat spectaculaire avec un scénario captivant.', 'https://images.pexels.com/photos/7768663/pexels-photo-7768663.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 4.6, 'PS4 / Xbox / PC', true, 40),
  ('Injustice: Gods Among Us', 'injustice', 'Injustice', 12000, 'Le premier opus de la saga Injustice. Batman face à Superman dans un monde où les lignes sont brouillées.', 'https://images.pexels.com/photos/38576037/pexels-photo-38576037.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 4.4, 'PS4 / Xbox', false, 25),
  ('EA Sports FC 24', 'sport', 'Sport', 25000, 'Le football nouvelle génération avec HyperMotion V, des animations réalistes et tous les championnats du monde.', 'https://images.pexels.com/photos/1657324/pexels-photo-1657324.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 4.5, 'PS5 / Xbox / PC', true, 80),
  ('Football 2023', 'sport', 'Sport', 15000, 'Profitez du football avec des matchs rapides, des ligues internationales et un mode carrière complet.', 'https://images.pexels.com/photos/36227922/pexels-photo-36227922.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 4.0, 'PS4 / Xbox', false, 50),
  ('Football 2024', 'sport', 'Sport', 18000, 'La nouvelle saison de football avec des graphismes améliorés, de nouveaux stades et un gameplay fluide.', 'https://images.pexels.com/photos/27576504/pexels-photo-27576504.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 4.2, 'PS5 / Xbox / PC', true, 55),
  ('eFootball 2024', 'sport', 'Sport', 10000, 'Le football free-to-play d''Konami avec des licences officielles, un mode en ligne et des joueurs légendaires.', 'https://images.pexels.com/photos/1657324/pexels-photo-1657324.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 3.9, 'PS5 / PC / Mobile', false, 100),
  ('Assassins Creed Mirage', 'action', 'Action', 22000, 'Incarniez Basim, un voleur devenu assassin dans le Bagdad du IXe siècle. Aventure, infiltration et parkour.', 'https://images.pexels.com/photos/26732100/pexels-photo-26732100.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 4.3, 'PS5 / Xbox / PC', true, 40),
  ('Spider-Man 2', 'action', 'Action', 28000, 'Swing through New York as Peter Parker and Miles Morales in this blockbuster action adventure.', 'https://images.pexels.com/photos/38576037/pexels-photo-38576037.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 4.9, 'PS5', true, 35),
  ('Grand Theft Auto V', 'action', 'Action', 20000, 'Explorez Los Santos avec trois protagonistes dans ce chef d''œuvre du monde ouvert. Action, aventure et liberté totale.', 'https://images.pexels.com/photos/11285597/pexels-photo-11285597.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 4.8, 'PS5 / Xbox / PC', false, 70),
  ('The Forest', 'survival', 'Survie', 12000, 'Survivez sur une île peuplée de cannibales après un crash d''avion. Construisez, explorez et restez en vie.', 'https://images.pexels.com/photos/3772353/pexels-photo-3772353.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 4.5, 'PC / PS4', false, 45),
  ('Resident Evil Village', 'survival', 'Survie', 20000, 'Affrontez l''horreur dans un village maudit en incarnant Ethan Winters. Survival horror à l''ambiance glaçante.', 'https://images.pexels.com/photos/19955805/pexels-photo-19955805.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 4.6, 'PS5 / Xbox / PC', true, 30),
  ('Subnautica', 'survival', 'Survie', 10000, 'Explorez les profondeurs d''une planète océanique. Construisez des bases, chassez et survivez aux créatures abyssales.', 'https://images.pexels.com/photos/13316187/pexels-photo-13316187.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 4.4, 'PC / PS5 / Xbox', false, 50),
  ('Minecraft Java & Bedrock', 'minecraft', 'Minecraft', 15000, 'Le jeu de construction infini. Minez, construisez, explorez un monde fait de blocs. Créatif ou survie, à vous de choisir.', 'https://images.pexels.com/photos/25696621/pexels-photo-25696621.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 4.9, 'PC / Console / Mobile', true, 200),
  ('Minecraft Dungeons', 'minecraft', 'Minecraft', 12000, 'Un dungeon crawler d''action dans l''univers Minecraft. Affrontez des hordes de monstres en coopération.', 'https://images.pexels.com/photos/22845394/pexels-photo-22845394.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 4.3, 'PC / Console', false, 60)
ON CONFLICT DO NOTHING;
